name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ b2.5, b3.0, master]
  pull_request:
    branches: [ b2.5, b3.0, master, SPARKC-651 ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: ccm pip installation
        uses: BSFishy/pip-action@v1
        with:
          packages: ccm

      - name: sbt tests
        env:
          TEST_PARALLEL_TASKS: 1
          CCM_CASSANDRA_VERSION: 4.0-beta4
        id: sbt
        uses: lokkju/github-action-sbt@8-1.3.0-2.11.12
        with:
          commands: test it:test